name: Generate and Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and Allure
        run: |
          npm install -g newman
          npm install -g allure-commandline

      - name: Run Newman Tests
        run: |
          newman run ./tests/JSONPlaceholderTests.postman_collection.json \
            -r junit --reporter-junit-export allure-results/results.xml

      - name: List Contents of allure-results Directory
        run: |
          echo "Contents of allure-results directory:"
          ls -la allure-results/

      - name: Display results.xml
        run: |
          echo "Contents of allure-results/results.xml:"
          cat allure-results/results.xml

      - name: Load Previous Allure History
        if: always()
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git clone --single-branch --branch gh-pages https://github.com/${GITHUB_REPOSITORY} gh-pages
          prev_run_number=$(( GITHUB_RUN_NUMBER - 1 ))
          echo "Previous run number: $prev_run_number"
          if [ -d "gh-pages/${prev_run_number}/history" ]; then
            echo "Previous history directory exists. Copying history..."
            mkdir -p allure-results/history
            cp -r gh-pages/${prev_run_number}/history/* allure-results/history/
          else
            echo "No history directory found for previous run."
          fi

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report --relative-base-url || { echo 'Allure report generation failed'; exit 1; }

      - name: List Contents of allure-report Directory
        run: |
          echo "Contents of allure-report directory:"
          ls -la allure-report/
          echo "Contents of allure-report/widgets directory:"
          ls -la allure-report/widgets/

      - name: Prepare Report for Deployment
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          mkdir -p gh-pages/${GITHUB_RUN_NUMBER}
          rsync -av --delete allure-report/ gh-pages/${GITHUB_RUN_NUMBER}/
          touch gh-pages/.nojekyll
          # Update index.html to redirect to the latest report
          echo '<meta http-equiv="refresh" content="0; url='${GITHUB_RUN_NUMBER}/index.html'">' > gh-pages/index.html
          echo "Contents of gh-pages/${GITHUB_RUN_NUMBER}/:"
          ls -la gh-pages/${GITHUB_RUN_NUMBER}/
          echo "Contents of gh-pages/${GITHUB_RUN_NUMBER}/widgets:"
          ls -la gh-pages/${GITHUB_RUN_NUMBER}/widgets/

      - name: Remove Old Reports (Keep Last 10)
        run: |
          cd gh-pages
          ls -d [0-9]*/ | sort -n | head -n -10 | xargs rm -rf || true

      - name: List Contents of gh-pages Directory Before Deployment
        run: |
          echo "Contents of gh-pages directory:"
          ls -la gh-pages/

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages
          keep_files: true
          allow_empty_commit: true
          exclude_assets: ''

      - name: Comment on Commit with Report Link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runNumber = process.env.GITHUB_RUN_NUMBER;
            const repositoryOwner = context.repo.owner;
            const repositoryName = context.repo.repo;
            const reportUrl = `https://${repositoryOwner}.github.io/${repositoryName}/${runNumber}/`;
            await github.rest.repos.createCommitComment({
              owner: repositoryOwner,
              repo: repositoryName,
              commit_sha: context.sha,
              body: `✅ Allure Report for build #${runNumber} is available at: ${reportUrl}`
            });
