name: Generate and Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and Allure
        run: |
          npm install -g newman
          npm install -g allure-commandline

      - name: Run Newman Tests
        run: |
          newman run ./tests/JSONPlaceholderTests.postman_collection.json \
            -r junit --reporter-junit-export allure-results/results.xml

      - name: List Contents of allure-results Directory
        run: |
          echo "Contents of allure-results directory:"
          ls -la allure-results/

      - name: Load Previous Allure History
        if: always()
        run: |
          git clone --single-branch --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          if [ -d "gh-pages/history" ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report --relative-base-url || { echo 'Allure report generation failed'; exit 1; }

      - name: List Contents of allure-report Directory
        run: |
          echo "Contents of allure-report directory:"
          ls -la allure-report/
          echo "Contents of allure-report/widgets directory:"
          ls -la allure-report/widgets/

      - name: Prepare Report for Deployment
        run: |
          cp -r allure-report/history/ gh-pages/history/
          cp -r allure-report/* gh-pages/

      - name: List Contents of gh-pages Directory Before Deployment
        run: |
          echo "Contents of gh-pages directory:"
          ls -la gh-pages/

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages

      - name: Comment on Commit with Report Link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repositoryOwner = context.repo.owner;
            const repositoryName = context.repo.repo;
            const reportUrl = `https://${repositoryOwner}.github.io/${repositoryName}/`;
            await github.rest.repos.createCommitComment({
              owner: repositoryOwner,
              repo: repositoryName,
              commit_sha: context.sha,
              body: `✅ Allure Report is available at: ${reportUrl}`
            });
