name: Generate and Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and Allure
        run: |
          npm install -g newman
          npm install -g allure-commandline --save-dev

      - name: Run Newman Tests
        run: |
          newman run ./tests/JSONPlaceholderTests.postman_collection.json -r junit --reporter-junit-export results.xml

      - name: Prepare Allure Results
        run: |
          mkdir -p allure-results
          mv results.xml allure-results/

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean --copy-resources -o allure-report

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

