name: Run API Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and Allure
        run: |
          npm install -g newman
          npm install -g allure-commandline --save-dev

      - name: Run Newman Tests
        run: |
          newman run ./tests/JSONPlaceholderTests.postman_collection.json -r junit --reporter-junit-export results.xml

      - name: Prepare Allure Results
        run: |
          mkdir -p allure-results
          mv results.xml allure-results/

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_1_TEST }}
          publish_dir: ./allure-report
          force_orphan: true



